### ISSUE TITLE
Add subworkflow definition in subWorkflowParam to docs

### ISSUE THREAD

**Issue by coderabhigupta** [orkes-io/docs#509]
Add change added in https://github.com/orkes-io/orkes-conductor/pull/1289 to https://orkes.io/content/reference-docs/operators/sub-workflow#input-parameters

**Comment by RizaFarheen** [comment]
Hi @coderabhigupta @c4lm 

Can you share the details of this update to be added.I don't have access to the PR linked in description

**Comment by Rajakavitha1** [comment]
Hi @coderabhigupta and @RizaFarheen I do see the input parameters here: https://github.com/orkes-io/orkesworkers/blob/main/data/workflow/image_convert_resize_multipleformat.json.

Please confirm if these need to be updated in the inputParameters Attribute here: https://orkes.io/content/reference-docs/operators/sub-workflow#input-parameters
