### ISSUE TITLE
Add API docs Secret Client for UPDATE_SECRET

### ISSUE THREAD

**Issue by coderabhigupta** [orkes-io/docs#518]
Add Update Secret API to https://orkes.io/content/category/ref-docs/api

**Comment by RizaFarheen** [comment]
Hi @coderabhigupta 

This doc is already added - https://orkes.io/content/reference-docs/system-tasks/update-secret

Can we close this?

**Comment by RizaFarheen** [comment]
Hi @coderabhigupta 

The system task doc is published - https://orkes.io/content/reference-docs/system-tasks/update-secret

Do we have any APIs for this to be added?
