### ISSUE TITLE
Extend documentation of Subworkflow execution from a parent workflow to be clearer on the taskToDomain behavior. 

### ISSUE THREAD

**Issue by wockerman** [orkes-io/docs#626]
**Is your feature request related to a problem? Please describe.**
I did not find back the default behaviour for taskToDomain when executing subworkflows. 

**Describe the solution you'd like**
I made a pull request that can be reviewed/merged that extends the documentation:  https://github.com/orkes-io/docs/pull/619

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by RizaFarheen** [comment]
Merged the changes. Thanks @wockerman
